---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4
  - name: debian-7
    driver_config:
      box: opscode-debian-7.4
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.4_chef-provisionerless.box
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[zarafa-sabredav::default]
    attributes:
      zarafa:
        backend_type: mysql
        mysql_password: test
        catchall_user: me@example.com
        timezone: Europe/Berlin
